services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: secret123

  web:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
    command: pytest
    depends_on:
      - web
