services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=flaskdb
      - DB_USER=flaskuser
      - DB_PASSWORD=secret123
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  test:
    image: python:3.11
    depends_on:
      - web
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && pytest --maxfail=1 --disable-warnings -q"
    depends_on:
      - web

volumes:
  pgdata:

