name: CI Test with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: flaskdb
          POSTGRES_USER: flaskuser
          POSTGRES_PASSWORD: secret123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image for web
        run: docker build -t devops-hello-web .

      - name: Run web container
        run: |
          docker run -d --name web \
            --network host \
            -e DATABASE_HOST=localhost \
            -e DATABASE_PORT=5432 \
            -e DATABASE_NAME=flaskdb \
            -e DATABASE_USER=flaskuser \
            -e DATABASE_PASSWORD=secret123 \
            -p 5000:5000 devops-hello-web

      - name: Wait for web to be healthy
        run: |
          for i in {1..10}; do
            curl http://localhost:5000/health && break
            echo "Waiting for web..."
            sleep 5
          done

      - name: Run tests
        run: pytest
